#!/bin/bash
# Useful bash functions
# Zhang Linghan

alias cls="clear && printf '\e[3J'"
alias ll="ls -alhF"

rc () {
    . ~/.bashrc
}

kills () {
    # Kill all jobs
    kill -9 $(jobs -p)
}

waitpid () {
    # Wait for process $1 to finish
    while kill -0 $1; do
        sleep 0.5
    done
}

rand () {
    # Print $1 random digits
    if [ "$#" -eq  "0" ]; then
        N=8
    else
        N=$1
    fi
    python -c "import random,sys; sys.stdout.write('{:0$N}'.format(random.randint(0,10**$N-1)))"
}

prefrepl () {
    # Prefix rename
    # $1 Old prefix
    # $2 New prefix
    for d in $1*; do
        mv $d ${d/$1/$2}
    done
}

sufrepl () {
    # Suffix rename
    # $1 Old suffix
    # $2 New suffix
    for d in *$1; do
        mv $d ${d/$1/$2}
    done
}

setcol () {
    # Set in file $1 column $2 to $3
    local tmp=$(mktemp)
    awk '{$'$2'="'$3'";print}' $1 > $tmp
    mv $tmp $1
}

# Manipulate batchfile

newseed () {
    # Set new seed at column 3 in batchfile $1
    local tmp=$(mktemp)
    awk 'BEGIN{r="'$(rand $((8*$(wc -l $1|cut -d " " -f 1))))'"}{$3=substr(r,NR*8-7,8);print}' $1 > $tmp
    mv $tmp $1
}

newrun () {
    # Increase run id in batchfile $1 and call newseed
    newseed $1
    local tmp=$(mktemp)
    awk '{$1=substr($1,1,length($1)-2) sprintf("%02d",substr($1,length($1)-1)+1);print}' $1 > $tmp
    mv $tmp $1
}

newruns () {
    # Generate r$1 from r($1-1)
    local n=$(printf "%02d" $(($1-1)))
    for f in *r$n.batch; do
        local ff=${f/r$n/r$1};
        cp $f $ff;
        newrun $ff;
    done
}

setT () {
    # Set the correct temperature at column 11 according to the name of batchfile $1 (e.g. T0140r01.batch)
    # For full study
    T=${1:1:4}
    local tmp=$(mktemp)
    awk '{$1="T" "'$T'" substr($1,6);$11="'${T:0:1}.${T:1}'";print}' $1 > $tmp
    mv $tmp $1
}

setdt () {
    # Extract dt from r01 and assign to batch file $1 at column 19
    local tmp=$(mktemp)
    awk '{"cat " substr($1,1,length($1)-1) "1/dt"|getline dt;split(dt,a);dt=a[1];$19=sprintf("%.1e",dt);print}' $1 > $tmp
    mv $tmp $1
}

chdt() {
    # Incresae dt in micro batch file $1 by factor $2
    local tmp=$(mktemp)
    awk '{$19=sprintf("%.1e",'$2'*$19);print}' $1 > $tmp
    mv $tmp $1
}
